# This file is managed by Salt
# Any local modifications will be overwritten

{% if search_domains %}
search {{ search_domains | join(' ') }}
{% endif %}

{% for nameserver in nameservers %}
nameserver {{ nameserver }}
{% endfor %}
