# This file is managed by Salt
# Any local modifications will be overwritten

[Resolve]
{#- Anycast DNS servers - prefer local site first #}
{%- if 'muc01' in salt['pillar.get']('netbox:site:slug', '') %}
DNS=2001:678:ed0:f000:: 185.150.99.255 2001:678:e68:f000:: 5.1.66.255
{%- elif 'vie01' in salt['pillar.get']('netbox:site:slug', '') %}
DNS=2001:678:e68:f000:: 5.1.66.255 2001:678:ed0:f000:: 185.150.99.255
{%- else %}
{#- Default anycast servers if site is unknown #}
DNS=2001:678:e68:f000:: 5.1.66.255 2001:678:ed0:f000:: 185.150.99.255
{%- endif %}
DNSSEC=allow-downgrade
DNSOverTLS=no
