# Set status bar
set -g status-left-length 60
set -g status-right-length 40
set -g status-left "%Y-%m-%d %H:%M | #(whoami)@#H | #[default]"
set -g status-right "| load #(cat /proc/loadavg | cut -d' ' -f 1-3) | #(uptime | cut -d',' -f 1 | cut -d' ' -f 3-) #[default]"

# Enable mouse support
set -g mouse on
# bind m to toggle mouse mode
bind m \
    if -F '#{mouse}' 'set -g mouse off; display "Mouse Mode: OFF"' 'set -g mouse on; display "Mouse Mode: ON"'

# bind S to enable/disable synchronized panes
bind S set synchronize-panes

# Reload config file with prefix + r
bind r source-file /etc/tmux.conf \; display-message "Config reloaded!"
