---

name: Python tests

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unittest:
    runs-on: ubuntu-latest
    name: unittest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
      - name: dhcp-server
        run: python3 -m unittest discover -s dhcp-server/tests -v
